"""Consumer-facing engine surface shared by the Claude Engine and CodexEngine.

Autoswitch, the extra, kickoff, and the CLI program against this, never
against provider internals.
"""

from __future__ import annotations

from pathlib import Path
from typing import Protocol, runtime_checkable

from openswap.models import AccountsSnapshot
from openswap.usage_store import UsageEntry


@runtime_checkable
class AccountEngine(Protocol):
    provider: str          # "claude" | "codex"
    backup_dir: Path

    def accounts_snapshot(self, fetch: set[str] | None = None) -> AccountsSnapshot: ...
    def usage_entries_by_account(
        self, fetch: set[str] | None = None, *, scheduled: bool = False
    ) -> dict[str, UsageEntry]: ...
    def set_poll_policy_inputs(self, threshold: float, models: tuple[str, ...]) -> None: ...
    def current_account_number(self) -> str | None: ...
    def has_live_login(self) -> bool: ...
    def live_identity(self) -> tuple[str, str] | None: ...
    def slot_identity(self, num: str | int) -> tuple[str, str] | None: ...
    def account_email(self, account_num: str) -> str: ...
    def account_kind_for(self, account_num: str) -> str: ...
    def switchable_account_numbers(self) -> list[str]: ...
    def read_account_credentials(self, account_num: str, email: str) -> str: ...
    def freshen_backup(self, number: str, email: str) -> str: ...
    def switch(self, strategy: str | None = None, json_output: bool = False) -> dict | None: ...
    def switch_to(self, identifier: str, json_output: bool = False, force: bool = False) -> dict | None: ...
    def set_account_disabled(self, identifier: str, disabled: bool) -> None: ...
    def remove_account(self, identifier: str, assume_yes: bool = False) -> None: ...
